name: Session Article Request
description: Request article creation from OpenSearchCon session video
title: "[Session] "
labels: ["session"]
body:
  - type: markdown
    attributes:
      value: |
        ## Session Video
  - type: input
    id: youtube_url
    attributes:
      label: YouTube URL
      description: URL of the session video
      placeholder: https://www.youtube.com/watch?v=...
    validations:
      required: true
  - type: input
    id: slug
    attributes:
      label: Slug
      description: Article slug (e.g., opensearchcon-kr-2025-session-title)
      placeholder: opensearchcon-kr-2025-...
    validations:
      required: true
